project_id = "mlbzblnertbarnpgqdpq"

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-capacity-alert]
verify_jwt = false

[functions.export-workshop]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.export-all-data]
verify_jwt = false

[functions.reassign-workshop]
verify_jwt = false

[functions.notify-admin-login]
verify_jwt = false
